## Aliases
alias vi="nvim"
alias vim="nvim"
alias b="bundle"
alias git="hub"
alias v="vagrant"
alias d="docker"
alias dc="docker-compose"
alias sudo="sudo -E "
alias diff="colordiff -u"
alias ctags="/usr/local/bin/ctags"
alias tf="terraform"
alias deckset="open -a Deckset"

## Abbreviations
abbr -a be "bundle exec"
abbr -a bb "brew bundle"
abbr -a gcoo "git-branch-fzf"
abbr -a docker-stop "docker ps -aq | xargs docker stop"
abbr -a docker-rm "docker ps -aq | xargs docker rm -f"
abbr -a docker-rmi "docker images -f dangling=true -q | xargs docker rmi -f"
