#!/bin/sh -eu

aws_sso_login() {
    if ! aws sts get-caller-identity > /dev/null 2>&1; then
        echo "Session expired, logging in to AWS SSO..."
        aws sso login
    fi
}

aws_sso_login

secret_id=$(aws secretsmanager list-secrets --query 'SecretList[].[Name]' --output text | fzf)

if [ "$secret_id" = "" ]; then
    exit 0
fi

echo "secret_id: ${secret_id}"

aws secretsmanager get-secret-value --secret-id "${secret_id}" --query 'SecretString' | jq fromjson
