## Visual

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'bling/vim-airline'
depends = ['vim-airline-themes']
hook_add = 'source ~/.config/nvim/plugins/vim-airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_auto_colors = 0
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_guide_size = 1

  autocmd VimEnter,Colorscheme * :hi SpecialKey       ctermfg=240
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermfg=240 ctermbg=237
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermfg=240 ctermbg=236
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

## Editor

[[plugins]]
repo = 'kana/vim-smartinput'
hook_add = '''
  " overwrite key bind
  inoremap <BS> <BS>
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  let g:neoterm_position = 'vertical'
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/plugins/ale.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

## deoplete

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#sources#rust#racer_binary = expand('~/.cargo/bin/racer')
  let g:deoplete#sources#rust#rust_source_path = '/src'

  set completeopt-=preview " disable preview
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'zchee/deoplete-docker'
on_ft = 'docker'
