## Visual

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'bling/vim-airline'
hook_add = 'source ~/.config/nvim/plugins/vim-airline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'mhinz/vim-signify'

## Editor

[[plugins]]
repo = 'kana/vim-smartinput'
hook_add = '''
  " overwrite key bind
  inoremap <BS> <BS>
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/plugins/ale.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-surround'

## deoplete

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#sources#rust#racer_binary = expand('~/.cargo/bin/racer')
  let g:deoplete#sources#rust#rust_source_path = '/src'

  set completeopt-=preview " disable preview
'''
