## Visual

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'bling/vim-airline'
hook_add = 'source ~/.config/nvim/plugins/vim-airline.vim'

# [[plugins]]
# repo = 'itchyny/lightline.vim'
# hook_add = '''
# let g:lightline = {
#       \ 'colorscheme': 'iceberg',
#       \ }
# '''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'mhinz/vim-signify'

## Editor

[[plugins]]
repo = 'kana/vim-smartinput'
hook_add = '''
  " overwrite key bind
  inoremap <BS> <BS>
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/plugins/ale.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = 'source ~/.config/nvim/plugins/language-client.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

# [[plugins]]
# repo = 'cocopon/vaffle.vim'
# hook_add = '''
#   nnoremap <silent> <F2> :Vaffle<CR>
#   nnoremap <silent> <F3> :Vaffle<CR>
# '''
#
# [[plugins]]
# repo = 'Shougo/defx.nvim'
# hook_add = 'source ~/.config/nvim/plugins/defx.vim'
