## Visual

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'bling/vim-airline'
hook_add = 'source ~/.config/nvim/plugins/vim-airline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'mhinz/vim-signify'

## Editor

[[plugins]]
repo = 'kana/vim-smartinput'
hook_add = '''
  " overwrite key bind
  inoremap <BS> <BS>
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/plugins/ale.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-surround'

## deoplete

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1

  set completeopt-=preview " disable preview
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
hook_add = '''
  let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
  let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
'''

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
hook_add = '''
  let g:deoplete#sources#rust#racer_binary = expand('~/.cargo/bin/racer')
  let g:deoplete#sources#rust#rust_source_path = expand('~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src')
'''

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'zchee/deoplete-docker'
on_ft = 'docker'

[[plugins]]
repo = 'pbogut/deoplete-elm'
on_ft = 'elm'

[[plugins]]
repo = 'mhartington/nvim-typescript'
build = './install.sh'
on_ft = 'typescript'
