brew 'age'
brew 'awscli'
brew 'awscli-local'
brew 'bash-language-server'
brew 'circleci'
brew 'clipper' { start_service true }
brew 'colima' { start_service true }
brew 'colordiff'
brew 'coreutils'
brew 'devcontainer'
brew 'direnv'
brew 'docker'
brew 'docker-buildx'
brew 'docker-compose'
brew 'docker-credential-helper'
brew 'ec2-instance-selector' { tap_name 'aws/tap' }
brew 'eza'
brew 'fd'
brew 'fish'
brew 'fzf'
brew 'gh'
brew 'ghalint'
brew 'ghq'
brew 'git'
brew 'git-secrets'
brew 'github-nippou' { tap_name 'masutaka/github-nippou' }
brew 'glow'
brew 'go'
brew 'graphviz'
brew 'helm'
brew 'heroku'
brew 'hub'
brew 'ipcalc'
brew 'jp'
brew 'jq'
brew 'krew'
brew 'kubectl' { directory_name 'kubernetes-cli' }
brew 'localstack-cli' { tap_name 'localstack/tap' }
brew 'lua-language-server'
brew 'mas'
brew 'minikube'
brew 'neovim' { head true }
brew 'node'
brew 'opener' { start_service true; tap_name 'superbrothers/opener' }
brew 'phantom' { tap_name 'aku11i/tap' }
brew 'php'
brew 'pipx'
brew 'pstree'
brew 'python' { use_cellar_option true }
brew 'ripgrep'
brew 'ruby'
brew 'rust-analyzer'
brew 'rustup-init'
brew 's3-edit' { tap_name 'tsub/s3-edit' }
brew 'sops'
brew 'stern'
brew 'terminal-notifier'
brew 'terraform' { tap_name 'hashicorp/tap' }
brew 'terraform-docs'
brew 'terraform-local'
brew 'terraform-ls'
brew 'terragrunt'
brew 'tflint'
brew 'tig'
brew 'tmux'
brew 'tmuxp'
brew 'tree'
brew 'typescript'
brew 'uv'
brew 'watch'
brew 'whalebrew'
brew 'yamlls' { tap_name 'tsub/yamlls' }
brew 'yarn'
brew 'yq'
