brew 'amazon-ecs-cli'
brew 'aws-sam-cli'
brew 'awscli'
brew 'b4b4r07/gist/gist' do
  directory_name 'gist'
end
brew 'colordiff'
brew 'ctop'
brew 'direnv'
brew 'dive'
brew 'eksctl'
brew 'elm'
brew 'exa'
brew 'fd'
brew 'fillin'
brew 'fish'
brew 'fzf'
brew 'ghq'
brew 'gibo'
brew 'git'
brew 'git-secrets'
brew 'github-nippou'
brew 'gnupg'
brew 'go'
brew 'go-swagger'
brew 'goenv'
brew 'heroku'
brew 'hub'
brew 'ipcalc'
brew 'jq'
brew 'kompose'
brew 'kube-aws'
brew 'kubectl' do
  directory_name 'kubernetes-cli'
end
brew 'kubectx'
brew 'kubernetes-helm'
brew 'kustomize'
# brew 'neovim'
brew 'nodenv'
brew 'packer'
brew 'pet'
brew 'pget'
brew 'pinentry-mac'
brew 'pstree'
brew 'python'
brew 'python@2'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'rustup-init'
brew 's3-edit'
brew 'shellcheck'
brew 'skaffold'
brew 'stern'
brew 'terminal-notifier'
brew 'tfenv'
brew 'tfschema'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'universal-ctags' do
  head true
end
brew 'urlview'
brew 'yarn'
