tap 'aws/tap'
tap 'b4b4r07/gist'
tap 'code-hex/pget'
tap 'heroku/brew'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'itchyny/fillin'
tap 'knqyf263/pet'
tap 'knqyf263/utern'
tap 'masutaka/github-nippou'
tap 'melonamin/formulae'
tap 'minamijoyo/tfschema'
tap 'saadparwaiz1/personal'
tap 'tsub/s3-edit'
tap 'tsub/yamlls' { uri 'git@github.com:tsub/homebrew-yamlls.git' }
tap 'universal-ctags/universal-ctags'
tap 'wagoodman/dive'
