# Aliases
alias vi="nvim"
alias vim="nvim"
alias b="bundle"
alias be="bundle exec"
alias bb="brew bundle"
alias git="hub"
alias gcoo="git-branch-fzf"
alias la="ls -al"
alias rm="rm -i"
alias v="vagrant"
alias diff="colordiff -u"
alias ctags="/usr/local/bin/ctags"
alias sudo="sudo -E "
alias d="docker"
alias dc="docker-compose"
alias docker-stop="docker ps -aq | xargs docker stop"
alias docker-rm="docker ps -aq | xargs docker rm -f"
alias docker-rmi="docker images -f dangling=true -q | xargs docker rmi -f"
alias tf="terraform"
alias deckset="open -a Deckset"
