brew 'amazon-ecs-cli'
brew 'awscli'
brew 'b4b4r07/gist/gist' { directory_name 'gist' }
brew 'colordiff'
brew 'ctop'
brew 'direnv'
brew 'dive'
brew 'eksctl'
brew 'elm'
brew 'exa'
brew 'fd'
brew 'fillin'
brew 'fish'
brew 'fzf'
brew 'ghq'
brew 'gibo'
brew 'git'
brew 'git-secrets'
brew 'github-nippou'
brew 'gnupg'
brew 'go'
brew 'goenv'
# brew 'heroku' # macOS only
brew 'hub'
brew 'ipcalc'
brew 'jq'
brew 'kompose'
brew 'kube-aws'
brew 'kubectl' { directory_name 'kubernetes-cli' }
brew 'kubectx'
brew 'helm'
brew 'kustomize'
brew 'neovim'
brew 'nodenv'
brew 'packer'
brew 'pet'
brew 'pget'
# brew 'pinentry-mac' # macOS only
brew 'pstree'
brew 'python@3.8'
brew 'rbenv'
brew 'ripgrep'
# brew 'rustup-init' # failed to build
brew 's3-edit'
brew 'shellcheck'
brew 'skaffold'
brew 'stern'
# brew 'terminal-notifier' # macOS only
brew 'terraform-ls'
brew 'tfenv'
brew 'tfschema'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
# brew 'universal-ctags' { head true } # failed to build
# brew 'urlview' # failed to build
brew 'yarn'
